### PR TITLE
Fix copy and paste error

### PR DESCRIPTION
**Pull request by jonashaag**
'to_pickle' does not support the 'index' parameter

### CODE REVIEW

**Comment by jonashaag** [comment]
Will not sign any CLA but hereby put the changes under public domain so you may merge anyways

**Comment by rlenain** [comment]
Hi @jonashaag. Thanks for your input, that's very valuable. 

Unfortunately we require anyone who wishes to contribute to Surfboard to sign the CLA. I will not be able to merge this until you do. 

If you prefer however, I can make this change myself.

**Comment by jonashaag** [comment]
Yes please

**Comment by rlenain** [comment]
This has been fixed now. Please pull the latest master version. Thanks very much!

**Pull request closed without merging**
